apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eowmkbvnj-nodejs 
  janus-idp.io/tekton: eowmkbvnj-nodejs
  backstage.io/kubernetes-id: eowmkbvnj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eowmkbvnj-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  