apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eowmkbvnj-nodejs
  janus-idp.io/tekton: eowmkbvnj-nodejs
  backstage.io/kubernetes-id: eowmkbvnj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eowmkbvnj-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
